services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    pull_policy: always
    ports:
      - "2283:2283"
    volumes:
      - /srv/containers/immich/photos:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: database
      DB_USERNAME: immich
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      IMMICH_LOG_LEVEL: log
      TZ: Europe/Berlin
    secrets:
      - db_password
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:2283/api/server/ping >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: release-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    pull_policy: always
    volumes:
      - /srv/containers/immich/model-cache:/cache
    environment:
      IMMICH_LOG_LEVEL: log
      TZ: Europe/Berlin
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c ''import urllib.request; urllib.request.urlopen("http://localhost:3003/ping")'' || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  redis:
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    volumes:
      - immich_redis_data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    secrets:
      - db_password
    volumes:
      - immich_postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

#--------------------------------------------------------------------------
# Volumes - for persistent data
#--------------------------------------------------------------------------
volumes:
  immich_postgres_data:
    name: immich_postgres_data
  immich_redis_data:
    name: immich_redis_data

#--------------------------------------------------------------------------
# Secrets - for sensitive data
#--------------------------------------------------------------------------
secrets:
  db_password:
    file: /srv/secrets/immich/db_password
